### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by yjy00** [yjy00/furima-25390#9]

**Comment by naokihayasan127** [comment]
ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
・他のユーザーが投稿したプロトタイプの編集ページにURLを直接入力して遷移しようとすると、トップページにリダイレクトされる。
/editと投稿者以外のユーザーがURLを打つと編集できてしまうので編集できないようにしましょう。

・SOLD OUTの購入済みの商品が編集・削除できてしまう。
こちら、購入済みの商品に関しては編集も削除もできないようにしましょう。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by naokihayasan127** [comment]
ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します
